package com.urbsource.controllers;

import java.sql.Date;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.urbsource.db.*;
import com.urbsource.models.*;

/**
 * Controller class to expose Comment CRUD functionalities via web APIs.
 * 
 * @author Mehmet Emre
 */
@Controller
@RequestMapping("/experience/*")
public class ExperienceController {
	
	JDBCUserDAO userDao;
	JDBCTagDAO tagDao;
	JDBCExperienceDAO expDao;
	JDBCExperienceVoteDAO voteDao;
	JDBCCommentDAO commentDao;

	/**
	 * Default constructor. Called by Spring framework to initialize controller.
	 */
	public ExperienceController(){
		userDao = new JDBCUserDAO();
		tagDao = new JDBCTagDAO();
		expDao = new JDBCExperienceDAO(userDao, tagDao);
		voteDao = new JDBCExperienceVoteDAO();
		commentDao = new JDBCCommentDAO(userDao);
	}

	/**
	 * Return a combination of recent and popular experiences as a JSON object. JSON object conversion is done by Spring.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/recent", method=RequestMethod.GET)
	public @ResponseBody HashMap<String,Object> recentAndPopular(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("experiences", expDao.getRecentAndPopularExperiences(10));
		return map;
	}

	/**
	 * Return a User's experiences as a JSON object. User ID is given from URL.
	 * 
	 * @author Mehmet Emre
	 * @param userId ID of user whose experiences are requested.
	 * @param model Data model generated by Spring
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/user/json/{userId}", method=RequestMethod.GET)
	public @ResponseBody HashMap<String,Object> userExperienceJSON(@PathVariable(value="userId") int userId, HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("experiences", expDao.getExperiences(userDao.getUser(userId)));
		return map;
	}

	/**
	 * Return a User's experiences with corresponding JSP view. User ID is given from URL.
	 * 
	 * @author Mehmet Emre
	 * @param userId ID of user whose experiences are requested.
	 * @param model Data model generated by Spring
	 * @return Data model and view to represent a User's experiences.
	 */
	@RequestMapping(value="/user/{userId}", method=RequestMethod.GET)
	public ModelAndView userInfo(@PathVariable(value="userId") int userId, Model model) {
		User u = new User();
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (!(auth instanceof AnonymousAuthenticationToken)) {
			u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
		}
		model.addAttribute("user", u);
		return new ModelAndView("user_experience_list", "user_", userDao.getUser(userId));
	}

	/**
	 * Return an experience's details with corresponding JSP view. User ID is given from URL.
	 * 
	 * @author Mehmet Emre
	 * @param id ID of experience whose details are requested.
	 * @param model Data model generated by Spring
	 * @return Data model and view to represent a User's experiences.
	 */
	@RequestMapping(value="/id/{id}", method=RequestMethod.GET)
	public ModelAndView getExperience(@PathVariable(value="id") int id, Model model) {
		User u = new User();
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (!(auth instanceof AnonymousAuthenticationToken)) {
			u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
		}
		Experience exp = expDao.getExperience(id);
		model.addAttribute("user", u);
		model.addAttribute("comments", commentDao.getComments(exp));
		return new ModelAndView("experience_details", "experience", exp);
	}

	/**
	 * Create a new experience. Experience content is extracted from {@link request}
	 * parameter.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/create", method=RequestMethod.POST)
	public @ResponseBody HashMap<String, Object> create(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to create experience");
			return map;
		}
		User u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
		JSONArray tagArray = json.getJSONArray("tags");
		Tag tags[] = new Tag[tagArray.length()];
		for (int i = 0, len = tagArray.length(); i < len; ++i)
			tags[i] = tagDao.getTag(tagArray.getString(i));
		
		Timestamp date;
		try {
		    DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); 
	        java.util.Date creationDate = df.parse(json.getString("date"));
			date = new Timestamp(creationDate.getTime());
		} catch (Exception e) {
			date = new Timestamp(new java.util.Date().getTime());
		}
		Experience exp = new Experience(u, json.getString("text"), tags).setMood(json.getString("mood")).setCreationTime(date);
		try {
		    DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); 
	        java.util.Date expirationDate = df.parse(json.getString("expirationDate"));
			exp.setExpirationDate(new Date(expirationDate.getTime()));
		} catch (Exception e) {
			exp.setExpirationDate(null);
		}
		exp.setLocation(json.getString("location"));
		map.put("success", expDao.createExperience(exp));
		return map;
		
	}

	/**
	 * Delete an experience. Experience ID is extracted from {@link request}
	 * parameter.
	 * 
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/delete", method=RequestMethod.POST)
	public @ResponseBody HashMap<String, Object> delete(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to delete your experiences");
			return map;
		}
		int id;
		try {
			id = json.getJSONObject("params").getInt("id");
		} catch (JSONException e) {
			map.put("success", false);
			map.put("error", "Experience ID is not given or not int, check how you call the API!");
			return map;
		}
		User u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
		Experience exp = expDao.getExperience(id);
		if (u.getId() != exp.getAuthor().getId()) {
			map.put("success", false);
			map.put("error", "You cannot delete others' experiences");
			return map;
		}
		map.put("success", expDao.deleteExperience(exp));
		return map;
		
	}

	/**
	 * Downvote an experience or undo a downvote. Experience ID and undo option are extracted from {@link request}
	 * parameter.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/downvote", method=RequestMethod.POST)
	public @ResponseBody HashMap<String,Object> downvote(HttpServletRequest request, HttpServletResponse response, Model model) {
		HashMap<String, Object> map = new HashMap<String, Object>();
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to vote experiences");
			return map;
		}
		try {
			JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
			int exp_id = json.getInt("id");
			boolean undo = json.getBoolean("undo");
			User u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
			Experience exp = expDao.getExperience(exp_id);
			if (undo)
				map.put("success", voteDao.deleteVote(exp, u));
			else
				map.put("success", voteDao.saveVote(exp, u, false));
		} catch (Exception e) {
			map.put("success", false);
			map.put("error", e.getMessage());
		}
		return map;
	}
	
	/**
	 * Upvote an experience or undo a upvote. Experience ID and undo option are extracted from {@link request}
	 * parameter.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/upvote", method=RequestMethod.POST)
	public @ResponseBody HashMap<String,Object> upvote(HttpServletRequest request, HttpServletResponse response, Model model) {
		HashMap<String, Object> map = new HashMap<String, Object>();
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to vote experiences");
			return map;
		}
		try {
			JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
			int exp_id = json.getInt("id");
			boolean undo = json.getBoolean("undo");
			User u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
			Experience exp = expDao.getExperience(exp_id);
			if (undo)
				map.put("success", voteDao.deleteVote(exp, u));
			else
				map.put("success", voteDao.saveVote(exp, u, true));
		} catch (Exception e) {
			map.put("success", false);
			map.put("error", e.getMessage());
		}
		return map;
	}
	/**
	 * This method gets tag list according to search query. Query comes from search box in tag option mode, 
	 * and results are shown in dropdown.
	 * @author Setenay Ronael
	 * @param request
	 * @param response
	 * @return
	 * @throws JSONException
	 * @throws IOException
	 */
	@RequestMapping(value="/searchTag", method=RequestMethod.POST)
	public @ResponseBody HashMap<String,Object> searchTag(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		map.put("tagList", expDao.getTagList(json.getJSONObject("params").getString("query")));
		return map;
	}
	
	/**
	 * This method gets experiences with selected tags.
	 * @author Setenay Ronael
	 * @param request
	 * @param response
	 * @return
	 * @throws JSONException
	 * @throws IOException
	 */
	@RequestMapping(value="searchExperienceTag", method=RequestMethod.POST)
	public @ResponseBody HashMap<String,Object> searchExperienceTag(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		JSONArray json2 = json.getJSONObject("params").getJSONArray("tags");
		Tag[] tags = new Tag[json2.length()];
		for(int i =0; i<json2.length();i++){
			tags[i] = new Tag(json2.getJSONObject(i).getString("name"),json2.getJSONObject(i).getInt("id"));
		}
		map.put("experiences", expDao.getSimilarExperiences(tags));
		return map;
	}
	
	/**
	 * This method gets experiences which explanation contains query.
	 * @author Setenay Ronael
	 * @param request
	 * @param response
	 * @return
	 * @throws JSONException
	 * @throws IOException
	 */
	@RequestMapping(value="searchExperienceText", method=RequestMethod.POST)
	public @ResponseBody HashMap<String,Object> searchExperienceText(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		map.put("experienceList", expDao.searchExperiences(json.getJSONObject("params").getString("text")));
		return map;
	}

	/**
	 * Extract body of given request and return the body embedded in a JSON-encoded string.
	 * 
	 * @param request HTTP request whose body will be extracted
	 * @return a JSON-encoded string containing the request body
	 * @author Setenay Ronael
	 */
	public String getBody(HttpServletRequest request) throws IOException
	{
		String body = null;
		StringBuilder stringBuilder = new StringBuilder();
		BufferedReader bufferedReader = null;
		try {
			InputStream inputStream = request.getInputStream();
			if (inputStream != null) {
				bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
				char[] charBuffer = new char[128];
				int bytesRead = -1;
				while ((bytesRead = bufferedReader.read(charBuffer)) > 0) {
					stringBuilder.append(charBuffer, 0, bytesRead);
				}
			} else {
				stringBuilder.append("");
			}
		} catch (IOException ex) {
			throw ex;
		} finally {
			if (bufferedReader != null) {
				try {
					bufferedReader.close();
				} catch (IOException ex) {
					throw ex;
				}
			}
		}
		body = stringBuilder.toString();
		body = "{ \"result\": "+body + "}";
		return body;
	}
	
	/**
	 * Update an experience. Experience content and ID are extracted from {@link request}
	 * parameter.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/update", method=RequestMethod.POST)
	public @ResponseBody HashMap<String, Object> update(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to update your experiences");
			return map;
		}
		int id;
		try {
			id = json.getInt("id");
		} catch (JSONException e) {
			map.put("success", false);
			map.put("error", "Experience ID is not given or not int, check how you call the API!");
			return map;
		}
		User u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
		Experience exp = expDao.getExperience(id);
		if (u.getId() != exp.getAuthor().getId()) {
			map.put("success", false);
			map.put("error", "You can update only your experiences!");
			return map;
		}
		JSONArray tagArray = json.getJSONArray("tags");
		Tag tags[] = new Tag[tagArray.length()];
		for (int i = 0, len = tagArray.length(); i < len; ++i)
			tags[i] = tagDao.getTag(tagArray.getString(i));
		HashSet<Tag> oldTags = new HashSet<Tag>(exp.getTags());
		oldTags.removeAll(Arrays.asList(tags));
		for (Tag t : oldTags) {
			exp.removeTag(t);
		}
		for (Tag t : tags) {
			exp.addTag(t);
		}
		exp.setText(json.getString("text"));
		expDao.saveExperience(exp);
		map.put("success", true);
		return map;
	}
	
	/**
	 * This method updates experiences explanation.
	 * @author Setenay Ronael
	 * @param request
	 * @param response
	 * @return
	 * @throws JSONException
	 * @throws IOException
	 */
	@RequestMapping(value="/editText", method=RequestMethod.POST)
	public @ResponseBody HashMap<String, Object> updateText(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result").getJSONObject("params");
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to update your experiences");
			return map;
		}
		int id;
		try {
			id = json.getInt("id");
		} catch (JSONException e) {
			map.put("success", false);
			map.put("error", "Experience ID is not given or not int, check how you call the API!");
			return map;
		}
		User u = userDao.getLoginUser(((UserDetails) auth.getPrincipal()).getUsername());
		Experience exp = expDao.getExperience(id);
		if (u.getId() != exp.getAuthor().getId()) {
			map.put("success", false);
			map.put("error", "You can update only your experiences!");
			return map;
		}
		exp.setText(json.getString("text"));
		expDao.saveExperience(exp);
		map.put("success", true);
		return map;
	}
	
	/**
	 * Clean up expired transient experiences.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/cleanUpExpired")
	public @ResponseBody HashMap<String, Object> cleanUpExpired(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("count", expDao.cleanUpExpiredExperiences());
		return map;
		
	}
	
	/**
	 * Mark an experience as spam by user. Experience ID is extracted from {@link request}
	 * parameter.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/markSpam", method=RequestMethod.POST)
	public @ResponseBody HashMap<String, Object> markSpam(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to report spam");
			return map;
		}
		int id;
		try {
			id = json.getInt("id");
		} catch (JSONException e) {
			map.put("success", false);
			map.put("error", "Experience ID is not given or not int, check how you call the API!");
			return map;
		}
		Experience exp = expDao.getExperience(id);
		map.put("success", expDao.markSpam(exp));
		return map;
	}
	
	/**
	 * Remove spam mark put by user from an experience. Experience ID is extracted from {@link request}
	 * parameter.
	 * 
	 * @author Mehmet Emre
	 * @param request HTTP request to this address
	 * @param response HTTP response object that this method will affect
	 * @return A {@link HashMap} that will be converted to a JSON object containing result and error messages.
	 */
	@RequestMapping(value="/unmarkSpam", method=RequestMethod.POST)
	public @ResponseBody HashMap<String, Object> unmarkSpam(HttpServletRequest request, HttpServletResponse response) throws JSONException, IOException{
		HashMap<String, Object> map = new HashMap<String, Object>();
		JSONObject json = (new JSONObject(getBody(request))).getJSONObject("result");
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof AnonymousAuthenticationToken) {
			map.put("success", false);
			map.put("error", "You must log in to undo your spam report");
			return map;
		}
		int id;
		try {
			id = json.getInt("id");
		} catch (JSONException e) {
			map.put("success", false);
			map.put("error", "Experience ID is not given or not int, check how you call the API!");
			return map;
		}
		Experience exp = expDao.getExperience(id);
		map.put("success", expDao.unmarkSpam(exp));
		return map;
	}
}